theme: jekyll-theme-minimal
title: Tammy Diehl
description: Data Science Portfolio
logo: "/images/climbing_pic.jpg"
show_downloads: "false"
 
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
